[package]
name = "node-rpc"
version = "0.1.0"

[dependencies]
futures = "0.1.25"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-http-server = { git = "https://github.com/paritytech/jsonrpc" }
log = "0.4"
serde = "1.0"
serde_derive = "1.0"

node-runtime = { path = "../runtime" }
primitives = { path = "../../core/primitives" }

[dev-dependencies]
jsonrpc-test = { git = "https://github.com/paritytech/jsonrpc" }
serde_json = "1.0.0"
